### ISSUE TITLE
用 transform 翻转元素 

### ISSUE THREAD

**Issue by rupertqin** [rupertqin/jsCode#23]
```css
el {
    -moz-transform: scaleX(-1);
     -o-transform: scaleX(-1);
     -webkit-transform: scaleX(-1);
     transform: scaleX(-1);
     filter: FlipH;
     -ms-filter: "FlipH";
}
```
