### ISSUE TITLE
图片预加载

### ISSUE THREAD

**Issue by rupertqin** [rupertqin/jsCode#39]
用 CSS 在伪元素上加多个背景的方法

```css
:root:before {
        content: url(http://davidwalsh.name/wp-content/themes/walshbook3/images/sprite.png)
                url(https://sf-sponsor.b0.upaiyun.com/f154ab441ca3a4739314f8322ce63711.png)
                url(https://sfault-avatar.b0.upaiyun.com/367/392/3673921662-56fe4c96d17ad_big64)
                url(https://sf-static.b0.upaiyun.com/v-5732db60/global/img/pattern/6.svg)
                url(https://sf-static.b0.upaiyun.com/v-5732db60/global/img/pattern/9.svg)
                ;
        position: absolute;
        visibility: hidden;
        left: -9999em;
}
```
